### ISSUE TITLE
Draft

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-universe#1]
Initial mockup.

![image](https://cloud.githubusercontent.com/assets/2152766/13548910/ef0f65f2-e2f2-11e5-8706-70b11a506e33.png)

**Comment by mottosso** [comment]
Concept.

![image](https://cloud.githubusercontent.com/assets/2152766/13585325/1522961c-e4b3-11e5-9da4-5f2de7158215.png)

In short, the website is a case of many inputs and one output. The central piece is Firebase, an online JSON-based database. Many producers append data, such as GitHub events, announcements, blog updates et. cetera. A static webpage then reads from this database upon load, and dynamically updates whenever anything new happens.

Due to the simple nature of this setup, it means that the website itself can remain static; no need for an application. Which simplifies both development and deployment. It also means the producers can go down, both temporarily and permanently, without affecting the main website. Assuming GitHub pages and Firebase stays up, the website will continue to run. It also means I can send arbitrary updates from any location, even from a browser in an insecure location, and the website will be no wiser about the origins of its content.

The website will be built to support a series of inputs. Each input formatted in a certain way which determines how it is drawn. For example, a GitHub push event is drawn with an icon signifying a push and a short description of time, when and who, whereas a blog update event is given a different icon and a different styling, perhaps including a snippet of content to lure the user into reading the full thing. Larger items, such as announcements, are given large and bold text. And so forth.

**Types**

``` yaml
github-push: Someone pushed to *any* Pyblish repo on GitHub
github-clone: Someone cloned *any* Pyblish repo on GitHub
github-fork: Someone forked to *any* Pyblish repo on GitHub
github-issue: An issue was made in *any* Pyblish repo on GitHub
github-mention: A member of the Pyblish org was mentioned
github-starred: A Pyblish project was starrred
github-gist: A gist was created/modified
github-ping: GitHub says hi
github-comment: A comment was made in an issue
github-create: A repository was created
github-delete: A repository was removed :(
github-deploy: Something was deployed
github-deploy-status: How are things with that deployment?
github-wiki: A wiki was edited
github-member: A new member was added/removed from a team/repo
github-page-build: gh-pages was built
github-pullrequest: Someone requests a pull
github-repository-public: A repository was made public/private
github-release: A release was made
github-status: Travis status, for example.
github-team: A repository was added to a team
github-star: A repository was starred!
forum-newpost: A new post was made on the forums
forum-newthread: A new thread was made on the forums
forum-mention: Someone was mentioned on the forums
blog-newpost:
twitter-newpost:
announce: 
```
